export default {
  login: "emmalegend",
id: 48745609,
node_id: "MDQ6VXNlcjQ4NzQ1NjA5",
avatar_url: "https://avatars.githubusercontent.com/u/48745609?v=4",
gravatar_id: "",
url: "https://api.github.com/users/emmalegend",
html_url: "https://github.com/emmalegend",
followers_url: "https://api.github.com/users/emmalegend/followers",
following_url: "https://api.github.com/users/emmalegend/following{/other_user}",
gists_url: "https://api.github.com/users/emmalegend/gists{/gist_id}",
starred_url: "https://api.github.com/users/emmalegend/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/emmalegend/subscriptions",
organizations_url: "https://api.github.com/users/emmalegend/orgs",
repos_url: "https://api.github.com/users/emmalegend/repos",
events_url: "https://api.github.com/users/emmalegend/events{/privacy}",
received_events_url: "https://api.github.com/users/emmalegend/received_events",
type: "User",
site_admin: false,
name: "Emmanuel Effiong",
company: null,
blog: "",
location: "Lagos, Nigeria",
email: null,
hireable: true,
bio: "I am a Javascript Developer and i build web applications with it...",
twitter_username: "emmalegend",
public_repos: 30,
public_gists: 0,
followers: 0,
following: 0,
created_at: "2019-03-20T05:06:36Z",
updated_at: "2021-01-19T09:51:51Z"
};
